name: 'phpMAE CLI'
description: 'Executes a phpMAE CLI command.'
inputs:
  command:
    description: 'Command to execute.'
    required: true
    default: 'list'
  wdPath:
    description: 'Working directory path'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WD_PATH: ${{ inputs.wdPath }} 
  args:
    - ${{ inputs.command }}    
